name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        string-value: ["alpha", "beta", "gamma"]

    steps:
      - uses: actions/checkout@v2
      - name: Process string value
        run: echo "String value ${{ matrix.string-value }} processed" >> result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v2
        with:
          name: string-result-${{ matrix.string-value }}
          path: result.txt

  gather-results:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all result files
        uses: actions/download-artifact@v2
        with:
          name: string-result-*
          path: ./artifacts
      - name: Aggregate results
        run: |
          echo "String values processed in build:"
          for file in ./artifacts/*; do
            cat $file
          done
      - name: Deploy (example step)
        run: echo "Deploying application with the aggregated results..."
