name: Works

on:
  push:
    branches: ["**"]

jobs:
  parallel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        option: ["a", "b"]
    steps:
      - name: Create shared directory
        run: mkdir -p $GITHUB_WORKSPACE/shared
      - name: Process string value
        run: echo "${{ matrix.option }} processed" > $GITHUB_WORKSPACE/shared/result-${{ matrix.option }}.txt
      - name: List shared directory contents
        run: ls -l $GITHUB_WORKSPACE/shared
      - name: Debug: Show current job's result
        run: cat $GITHUB_WORKSPACE/shared/result-${{ matrix.option }}.txt

  gather-results:
    needs: parallel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List shared directory contents
        run: ls -l $GITHUB_WORKSPACE/shared
      - name: Aggregate results
        run: |
          for file in $GITHUB_WORKSPACE/shared/*; do
            echo "Content of $file:"
            cat $file
          done
      - name: Deploy (example step)
        run: echo "Deploying application with the aggregated results..."
