name: Works

on:
  push:
    branches: ["**"]

jobs:
  parallel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        option: ["a", "b"]

    steps:
      - uses: actions/checkout@v3
      - name: Create output
        run: echo "${{ matrix.option }} processed" > result-${{ matrix.option }}.txt
      - name: Upload result file
        uses: actions/upload-artifact@v2
        with:
          name: result-${{ matrix.option }}
          path: result-${{ matrix.option }}.txt
      - name: Verify upload
        run: ls -l result-${{ matrix.option }}.txt

  gather-results:
    needs: parallel
    runs-on: ubuntu-latest
    steps:
      - name: Download result a
        uses: actions/download-artifact@v2
        with:
          name: result-a
          path: ./artifacts
      - name: Download result b
        uses: actions/download-artifact@v2
        with:
          name: result-b
          path: ./artifacts
      - name: Verify download result a
        run: ls -l ./artifacts/result-a.txt
      - name: Verify download result b
        run: ls -l ./artifacts/result-b.txt
      - name: Aggregate results
        run: |
          echo "Aggregated results:"
          for file in ./artifacts/*; do
            echo "Content of $file:"
            cat $file
          done
      - name: Deploy (example step)
        run: echo "Deploying application with the aggregated results..."
