name: Conditional Workflow for Testing

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Enter comma-separated environments (e.g., "mona,sona,lisa")'
        required: true
        type: string
      runner:
        description: 'GitHub Actions runner'
        required: true
        type: string
        default: ubuntu-22.04
      workspace:
        required: true
        type: string
        description: 'GitHub Actions env'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      role: ${{ steps.set-role.outputs.role }}
    steps:
      - name: Set matrix from input
        id: set-matrix
        run: |
          INPUT="${{ github.event.inputs.environment }}"
          INPUT="${INPUT%,}"
          JSON_ARRAY="\"${INPUT//, /\",\"}\""
          echo "matrix=[$JSON_ARRAY]" >> $GITHUB_OUTPUT
          
      - name: Set AWS Role Based on workspace
        id: set-role
        run: |
          if [ "${{ github.event.inputs.workspace }}" == "dev" ]; then
            echo "role=arn:aws:iam::account-id:role/role-dev" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.workspace }}" == "stage" ]; then
            echo "role=arn:aws:iam::account-id:role/role-stage" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.workspace }}" == "prod" ]; then
            echo "role=arn:aws:iam::account-id:role/role-prod" >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.matrix) }}
        role: ${{ needs.setup.outputs.role }}
    steps:
      - name: Build and Deploy
        run: |
          echo "Deploying to environment: ${{ matrix.environment }} with role: ${{ matrix.role }}"

