name: Conditional Workflow for Testing

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Enter comma-separated environments (e.g., "mona,sona,lisa")'
        required: true
        type: string
      runner:
        description: 'GitHub Actions runner'
        required: true
        type: string
        default: ubuntu-22.04
      workspace:
        required: true
        type: string
        description: 'GitHub Actions env'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      role: ${{ steps.set-role.outputs.role }}
    steps:
      - name: Set matrix from input
        id: set-matrix
        run: |
          INPUT="${{ github.event.inputs.environments }}"
          INPUT="${INPUT%,}"
          JSON_ARRAY="\"${INPUT//, /\",\"}\""
          echo "matrix=[$JSON_ARRAY]" >> $GITHUB_OUTPUT
      - name: Set AWS Role Based on workspace
        id: set-role
        run: |
          ROLE="arn:aws:iam::account-id:role/role-${{ github.event.inputs.workspace }}"
          echo "role=$ROLE" >> $GITHUB_OUTPUT  # Output the role directly without JSON array brackets

  build:
    needs: setup
    runs-on: ${{ inputs.runner }}
    env:
      ROLE: ${{ needs.setup.outputs.role }}  # Set the role as an environment variable
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Build and Deploy
        run: |
          echo "Deploying to environment: ${{ matrix.environment }} with role: $ENV{ROLE}"


