name: Conditional Workflow for Testing

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Enter comma-separated environments (e.g., "mona,sona,lisa")'
        required: true
        type: string
      runner:
        description: 'GitHub Actions runner'
        required: true
        type: string
        default: ubuntu-22.04

jobs:
  setup:
    runs-on: ${{ inputs.runner }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix from input
        id: set-matrix
        run: |
          INPUT="${{ github.event.inputs.environments }}"
          INPUT="${INPUT%,}"  # Remove trailing comma if present
          JSON_ARRAY="\"${INPUT//, /\",\"}\""  # Format as JSON array
          echo "matrix=[$JSON_ARRAY]" >> $GITHUB_OUTPUT  # Use modern output method

  build:
    needs: setup
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.matrix) }}
    outputs:
      successful-envs: ${{ steps.collect-success.outputs.successful-envs }}
    steps:
      - name: Check echo from matrix
        run: echo "${{ matrix.environment }}"
      - name: Simulate Task Success
        run: |
          if [[ "${{ matrix.environment }}" == "mona" || "${{ matrix.environment }}" == "sona" ]]; then
            echo "${{ matrix.environment }}" >> successful-envs.txt
          fi
      - name: Collect Successful Environments
        id: collect-success
        run: |
          if [ -f successful-envs.txt ]; then
            SUCCESS_ENVS=$(cat successful-envs.txt | tr '\n' ',' | sed 's/,$//')
            echo "successful-envs=$SUCCESS_ENVS" >> $GITHUB_OUTPUT
          else
            echo "successful-envs=" >> $GITHUB_OUTPUT  # Ensure output is always set
          fi
  deploy:
    needs: build
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.build.outputs.successful-envs) }}
    if: ${{ needs.build.outputs.successful-envs != '' }}
    steps:
      - name: Deploy for Successful Environments
        run: |
          echo "Deploying to environment: ${{ matrix.environment }}"
          # Insert deployment commands here
