name: Conditional Workflow for Testing

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Enter comma-separated environments (e.g., "mona,sona,lisa")'
        required: true
        type: string
      runner:
        description: 'GitHub Actions runner'
        required: true
        type: string
        default: ubuntu-22.04
      workspace:
        required: true
        type: string
        description: 'GitHub Actions env'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      role: ${{ steps.set-role.outputs.role }}
    steps:
      - name: Set matrix from input
        id: set-matrix
        run: |
          INPUT="${{ github.event.inputs.environments }}"
          INPUT="${INPUT%,}"
          JSON_ARRAY="\"${INPUT//, /\",\"}\""
          echo "matrix=[$JSON_ARRAY]" >> $GITHUB_OUTPUT
      - name: Set AWS Role Based on workspace
        id: set-role
        run: |
          if [ "${{ github.event.inputs.workspace }}" == "dev" ]; then
            ROLE="arn:aws:iam::123456789012:role/role"
          elif [ "${{ github.event.inputs.workspace }}" == "stage" ]; then
            ROLE="arn:aws:iam::234567890123:role/role"
          elif [ "${{ github.event.inputs.workspace }}" == "prod" ]; then
            ROLE="arn:aws:iam::345678901234:role/role"
          fi
          echo "role=$ROLE" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Build and Deploy
        run: |
          echo "Deploying to environment: ${{ matrix.environment }} with role: ${{ env.ROLE }}"
    env:
      ROLE: ${{ needs.setup.outputs.role }}
        


